### PR TITLE
Set lazyredraw

### PR DESCRIPTION
**Pull request by briceburg**
In reference to #78 -- speeds up macro insertion, esp. on slower terminals. Please let me know if I can change anything. Thanks!

### CODE REVIEW

**Comment by justinmk** [comment]
https://github.com/tpope/vim-sensible/issues/78

**Comment by bruno-** [comment]
If voting will help to get this merged, I vote :+1:

**Comment by vheon** [comment]
:+1: so another line from my vimrc will be set by sensible :)

**Comment by justinmk** [comment]
Pretty sure voting does the opposite, per tpope's twitter.

**Comment by Mike-Now** [comment]
`lazyredraw` causes considerable lag with YCM plugin on

**Comment by tpope** [comment]
FINE

**Pull request closed without merging**
